"""
AIM Value Attribution Ledger (aim/core/value_attribution.py)
-----------------------------------------------------------
Tracks and proves the exact return on investment (WTP & ROI) generated by AIM:
- Campaign Dispatch Attribution
- Creator Escrow Marketing Attribution
- Competitor Counter-Strategy Absorption
- Search Rank Lift Attribution
Adheres strictly to Karpathy Principle 3 (Verify Obsessively) and Gate 0 Evidence Tiers.
"""

import uuid
from datetime import datetime
from typing import Dict, List, Any, Optional
from pydantic import BaseModel, Field


class AttributionEntry(BaseModel):
    entry_id: str
    tenant_id: str
    source_type: str  # CAMPAIGN_DISPATCH, CREATOR_ESCROW, RADAR_ABSORPTION, RANK_LIFT
    title: str
    units_generated: int
    unit_price: int
    gross_revenue_krw: int
    cost_incurred_krw: int
    net_value_krw: int
    evidence_tier: str = "C_ILLUSTRATIVE"
    recorded_at: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))


class TenantAttributionSummary(BaseModel):
    tenant_id: str
    business_name: str
    monthly_fee_krw: int
    cumulative_revenue_krw: int
    cumulative_cost_krw: int
    net_benefit_krw: int
    roi_multiplier: float
    total_campaigns: int
    evidence_tier: str = "C_ILLUSTRATIVE"
    entries: List[AttributionEntry]


class ValueAttributionLedger:
    """Central accounting ledger attributing economic value created for each subscriber."""

    def __init__(self):
        self.ledger: Dict[str, List[AttributionEntry]] = {
            "TENANT_001": [
                AttributionEntry(
                    entry_id="ATTR_001",
                    tenant_id="TENANT_001",
                    source_type="CAMPAIGN_DISPATCH",
                    title="주말 브런치 사전예약 타임어택",
                    units_generated=50,
                    unit_price=24000,
                    gross_revenue_krw=1200000,
                    cost_incurred_krw=0,
                    net_value_krw=1200000,
                    evidence_tier="C_ILLUSTRATIVE",
                    recorded_at="2026-10-04 11:30:00",
                ),
                AttributionEntry(
                    entry_id="ATTR_002",
                    tenant_id="TENANT_001",
                    source_type="CAMPAIGN_DISPATCH",
                    title="가을 무화과 신메뉴 얼리버드 알림",
                    units_generated=40,
                    unit_price=22000,
                    gross_revenue_krw=880000,
                    cost_incurred_krw=0,
                    net_value_krw=880000,
                    evidence_tier="C_ILLUSTRATIVE",
                    recorded_at="2026-09-28 14:00:00",
                ),
            ],
            "TENANT_002": [
                AttributionEntry(
                    entry_id="ATTR_101",
                    tenant_id="TENANT_002",
                    source_type="CAMPAIGN_DISPATCH",
                    title="추석 연휴 리커버리 리프팅 예약",
                    units_generated=15,
                    unit_price=350000,
                    gross_revenue_krw=5250000,
                    cost_incurred_krw=0,
                    net_value_krw=5250000,
                    evidence_tier="C_ILLUSTRATIVE",
                    recorded_at="2026-10-02 09:30:00",
                ),
            ],
        }

    def record_attribution(
        self,
        tenant_id: str,
        source_type: str,
        title: str,
        units_generated: int,
        unit_price: int,
        cost_incurred_krw: int = 0,
        evidence_tier: str = "C_ILLUSTRATIVE",
    ) -> AttributionEntry:
        gross = units_generated * unit_price
        net = gross - cost_incurred_krw

        entry = AttributionEntry(
            entry_id=f"ATTR_{uuid.uuid4().hex[:6].upper()}",
            tenant_id=tenant_id,
            source_type=source_type,
            title=title,
            units_generated=units_generated,
            unit_price=unit_price,
            gross_revenue_krw=gross,
            cost_incurred_krw=cost_incurred_krw,
            net_value_krw=net,
            evidence_tier=evidence_tier,
        )

        if tenant_id not in self.ledger:
            self.ledger[tenant_id] = []
        self.ledger[tenant_id].insert(0, entry)
        return entry

    def get_tenant_summary(self, tenant_id: str, monthly_fee_krw: int = 49000, business_name: str = "") -> TenantAttributionSummary:
        entries = self.ledger.get(tenant_id, [])
        total_rev = sum(e.gross_revenue_krw for e in entries)
        total_cost = sum(e.cost_incurred_krw for e in entries)
        net_ben = total_rev - total_cost

        # Total investment = subscription fee (2-month baseline amortized) + optional creator cost
        total_invested = (monthly_fee_krw * 2) + total_cost
        roi = round(total_rev / total_invested, 1) if total_invested > 0 else 0.0

        return TenantAttributionSummary(
            tenant_id=tenant_id,
            business_name=business_name or tenant_id,
            monthly_fee_krw=monthly_fee_krw,
            cumulative_revenue_krw=total_rev,
            cumulative_cost_krw=total_cost,
            net_benefit_krw=net_ben,
            roi_multiplier=roi,
            total_campaigns=len(entries),
            evidence_tier="C_ILLUSTRATIVE",
            entries=entries,
        )


# Singleton Ledger Instance
attribution_ledger = ValueAttributionLedger()
